### PR TITLE
Added few slides and code samples

### PR DESCRIPTION
**Pull request by Vathasav**
I have added slides about software growth and refactoring. Also, few code samples related to refactoring are added. Now the number of slides have increased, but I think we can skip some slides during the lecture depending on the time.

### CODE REVIEW

**Comment by bast** [comment]
Thanks! Great work.

Few questions:
- Some of the slides seem to use pseudocode (which would be fine) or is it an actual language? If pseudocode, we may want to indicate it.
- I agree that we can keep more slides and skip few but if you had to remove 3 slides, which ones would you remove?
- For the software growth slide it would be great to take some example project and plot the software growth over time (lines of code, number of functions, number of modules, number of contributors).

**Comment by bast** [comment]
Thank you!

**Comment by Vathasav** [comment]
Even if we can't cover all the code samples in the slides, I think it is a good idea to keep them. Interested people may look into them later. Slide about equational reasoning and concurrency can be removed. We are talking about concurrency but not giving any examples. I am quite new to Fortran, so maybe a slide about Fortran can be removed. Anyway, I will go through the material again and will modify/remove some slides.

**Comment by bast** [comment]
I agree, we can keep them around. Feel free to skip anything that you don't find essential.

**Pull request merged**
